# -*- coding: utf-8 -*-
"""BagOfWords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJtEVrvlEvoRO2s9JQG4jjPuyHJsD3pE
"""

import numpy as np
import re

#the words we want to exclude from the "bag of words"
def delete_words(sentence):
    stop_words = ['a']
    words = re.sub("[^\w]", " ",  sentence).split()
    words_cleaned = [w.lower() for w in words if w not in stop_words]
    return words_cleaned

#reduce the duplictaes
def reduce_duplicates(sentences):
    words = []
    for sentence in sentences:
        w = delete_words(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

def bag_of_words(sentence, words):
    sentence_words = delete_words(sentence)
    # frequency word count
    bag = np.zeros(len(words))
    for sw in sentence_words:
        for i,word in enumerate(words):
            if word == sw: 
                bag[i] += 1
                
    return np.array(bag)

sentences = ["Machine learning is great","Natural Language Processing is a complex field","Natural Language Processing is used in machine learning"]
vocabulary = reduce_duplicates(sentences)

bag_of_words("Machine learning is great", vocabulary)

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['BagOfWords.csv']))
# Dataset is now stored in a Pandas Dataframe

df.head()

df.Abstract

sentence = df.Abstract[0].split()
vocabulary = reduce_duplicates(sentence)
print(sentence)

bag_of_words(df.Abstract[1], vocabulary)

"""如果gender是0，就存在一个bag of words 里面"""